=İnşaat Firması Fatura Yönetim Sistemi

==== 1.Singleton Pattern
İçerik yönetim sistemi olarak hazırlanmış windows form projemizde 10 kusur kalem fatura türü bulunmaktadır her birinin de alanları farklıdır ortak alanlar da vardır.
Projemizde her formda ortak olarak bulunan başlangıç ve bitiş tarihi alanlarını veritabanında kaydedilmek üzere Türkiye için formatladık, ekleme güncelleme tarihlerinde ve sistemdeki log hatalarında kullanmak üzere 

==== 2.Factory Pattern

==== 3.Builder Pattern

Faturalar için ne kadar ücret harcanmış bunu kullanıcının görmesi için anaforma eklediğim grafikte Builder Pattern kullanıyorum. Veritabanından faturaları alıp gösteriyorum.

==== 4.Prototype Pattern
Asya inşaata ait 12 kalem fatura giderlerinin kaydını tuttuğumuz projemizde (yemek, kira, vergi vs) Id,ödeme tipi, fatura tutarı, tarihi alanları ortaktır.Diğer fatura tipleri bu genel prototipten türeyecektir.
==== 5.Abstract Factory Pattern
Faturala tipini girerek nesne oluşturmak için bir komut yazmadan nesneniz oluşmuş olur.Yani otomasyon sizin yerinize nesneyi oluşturur.

==== 7.Observer Pattern

Yeni bir fatura kaydedildiğinde sistemde tanımlı mail adresine bilgi gönderiyoruz.

==== 8.Command Pattern

Faturaları filtreleyip gridde gösteriyoruz. Bu gridden verileri alıp excel yahut word çıktısı olarak kullanıcıya sunmak için Command Pattern kullandım.

=== 9.Memento Pattern

=== 10.Adapter Pattern
Kodlarımız try catch içinde yazdık catch durumunda hatayı c klasörü altındaki log dosyamıza atıyoruz, hemde messagebox ile kullanıcıya bildiriyoruz.
tasarım kalıbını  dönüştürücü olarak kullanıyoruz, log ve mesaj 

AYŞENUR KOÇAK 160202124
